plugins:
  - rubocop-capybara
  - rubocop-rails

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#double-quotes

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'
