name: Rubocop
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.7'
      - run: bundle install
      - name: Rubocop
        run: rubocop -f github
