name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@7dc18ff0ca6e3630d3f29d2a85ebf6cc27ae9d6c
        with:
          ruby-version: '3.1.2'
      - run: bundle install
      - name: Run tests
        run: bin/rails test

